#!/bin/bash

# Note: you will need to build the apptitude/vapor image first:
# docker build -t apptitude/vapor vapor

WEB_CONTAINER=`docker-compose ps -q web`
WORKER_CONTAINER=`docker-compose ps -q worker`
WEB_IS_RUNNING=`docker inspect -f '{{.State.Running}}' $WEB_CONTAINER`
WORKER_IS_RUNNING=`docker inspect -f '{{.State.Running}}' $WEB_CONTAINER`

# Stop running containers
[ "$WEB_IS_RUNNING" == "true" ] && docker-compose stop web
[ "$WORKER_IS_RUNNING" == "true" ] && docker-compose stop worker

# Build
docker run -i --volume=$PWD/..:/app apptitude/vapor build "$@"

# Restart containers
[ "$WEB_IS_RUNNING" == "true" ] && docker-compose start web
[ "$WORKER_IS_RUNNING" == "true" ] && docker-compose start worker
