version: "3"
services:

    redis:
        image: redis:3
        restart: always

    database:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: test1234
            MYSQL_DATABASE: grader
        ports:
            - 3306:3306

    web:
        build: vapor
        volumes:
            - '..:/app'
        links:
            - redis:redis
            - database:database
        expose:
            - "8080"
        ports:
            - 80:8080
        command: ["run", "serve", "--env=docker"]

    worker:
        build: vapor-jdk
        volumes:
            - '..:/app'
        links:
            - redis:redis
            - database:database
        command: ["run", "worker", "--env=docker"]
